---
- name: Tibia-Char localhost create artifact
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: artifact_version
      prompt: "Please enter the version of the artifact to build"
      private: false
      default: "1.0.0"
  roles:
    - build
