---
- name: Setup server tools
  hosts: all
  become: true
  roles:
    - setup-nvim
  tags:
    - bootstrap

- name: Pre-flight checks
  hosts: all
  gather_facts: true
  become: true
  roles:
    - pre-flight
  tags:
    - preflight
    - deploy
    - full

- name: Tibia-Char localhost create artifact
  hosts: localhost
  vars_prompt:
    - name: artifact_version
      prompt: "Please enter the version of the artifact to build"
      private: false
      default: "1.0.0"
  tasks:
    - name: Share artifact version with subsequent plays
      set_fact:
        artifact_version: "{{ artifact_version }}"
  roles:
    - build
  tags:
    - build
    - deploy
    - full

#TODO: deploy also the crons and create the crontabs to run them when appropiate
#TODO: how i do the next deployments? cleaning the folder or what?
#TODO: acabar el dump de la db en stg lo tienes en /tmp
#TODO: acuerdate de volver a encryptar el ansible vault

- name: Deploy tibia-char to hosts
  hosts: all
  become: true
  pre_tasks:
    - name: Determine the correct artifact version
      set_fact:
        artifact_version: >-
          {%- if hostvars['localhost']['artifact_version'] is defined -%}
            {{ hostvars['localhost']['artifact_version'] | trim }}
          {%- elif manual_artifact_version != "" -%}
            {{ manual_artifact_version | trim }}
          {%- endif -%}

    - name: Prompt for version ONLY if not already defined by localhost
      ansible.builtin.pause:
        prompt: "Artifact version not found from build. Please enter the version to deploy"
      register: manual_input
      when: hostvars['localhost']['artifact_version'] is undefined

    - name: Fail if no version was provided at all
      fail:
        msg: "Deployment halted: No artifact version was provided."
      when: artifact_version == ""
  roles:
    - docker-install
    - deploy
    - env
    - run
    - migrations
    - health-check
    - cleanup
  environment: &deploy_env
    DATABASE_URL: "{{ database_url }}"
    DATABASE_NAME: "{{ database_name }}"
    DATABASE_USER: "{{ database_user }}"
    DATABASE_PASSWORD: "{{ database_password }}"
    SERVER_PORT: "{{ server_port }}"
    ENV: "{{ env }}"
    API_PROTOCOL: "{{ api_protocol }}"
    POSTHOG_SDK_API_KEY: "{{ posthog_sdk_api_key }}"
  tags:
    - deploy
    - full

- name: Update config only (no rebuild)
  hosts: all
  become: true
  roles:
    - env
    - run
    - health-check
  environment: *deploy_env
  tags:
    - config
    - restart
