---
- name: Import shared vars
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/shared/main.yml"
    name: shared

- name: Build Tibia Char Docker img
  community.docker.docker_image_build:
    name: "{{ shared.tibia_char_artifact }}:{{ artifact_version }}"
    path: "{{ shared.deploy_path }}"
    dockerfile: Dockerfile
  tags:
    - deploy
    - run

- name: Scale instances
  community.docker.docker_compose_v2:
    project_src: "{{ shared.deploy_path }}"
    state: present
    pull: missing
    build: always
    scale:
      tibia_char_server: 2
    env_files:
      - .env
  register: compose_scale_up
  tags:
    - deploy
    - run

- name: Show docker compose scale up results
  ansible.builtin.debug:
    var: compose_scale_up
  tags:
    - deploy
    - run

- name: Wait for the new container to be ready
  ansible.builtin.pause:
    seconds: 15
  tags:
    - deploy
    - run

- name: Scale back down to 1 instance
  community.docker.docker_compose_v2:
    project_src: "{{ shared.deploy_path }}"
    state: present
    scale:
      tibia_char_server: 1
    env_files:
      - .env
  register: compose_scale_down
  tags:
    - deploy
    - run

- name: Show docker compose scale down results
  ansible.builtin.debug:
    var: compose_scale_down
  tags:
    - deploy
    - run

- name: Prune old images
  ansible.builtin.command: docker image prune -f --filter "dangling=true"
  changed_when: true
  tags:
    - deploy
    - run