---
- name: Import shared vars
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/shared/main.yml"
    name: shared

- name: Create tmp build folder
  ansible.builtin.file:
    path: "{{ local_tmp_build_folder }}"
    state: directory
    mode: '0755'
  tags:
    - build
    - zip

- name: Remove tibia-char artifact if exists
  ansible.builtin.file:
    path: "{{ local_tmp_build_folder }}/{{ shared.tibia_char_artifact }}"
    state: absent
  tags:
    - build
    - zip

- name: Zip tibia-char app
  community.general.archive:
    path: "{{ local_project_folder }}/*"
    dest: "{{ local_tmp_build_folder }}/{{ shared.tibia_char_artifact }}"
    exclusion_patterns:
      - "node_modules/*"
      - "migrate"
    mode: '0644'
  tags:
    - build
    - zip
