---
- name: Import shared vars
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/shared/main.yml"
    name: shared

- name: Create .env file for docker
  ansible.builtin.file:
    path: "{{ shared.deploy_path }}/.env"
    state: touch
    mode: '0600'
    owner: aclaretdev
    group: aclaretdev
  tags:
    - deploy
    - config

- name: Write env vars into the .env file
  ansible.builtin.lineinfile:
    dest: "{{ shared.deploy_path }}/.env"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    mode: '0600'
  with_items:
    - key: DATABASE_URL
      value: "{{ database_url }}"
    - key: DATABASE_NAME
      value: "{{ database_name }}"
    - key: DATABASE_USER
      value: "{{ database_user }}"
    - key: DATABASE_PASSWORD
      value: "{{ adatabase_password }}"
    - key: SERVER_PORT
      value: "{{ server_port }}"
    - key: ENV
      value: "{{ env }}"
    - key: POSTHOG_SDK_API_KEY
      value: "{{ posthog_sdk_api_key }}"
  tags:
    - deploy
    - config
