---
- name: Import shared vars
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/shared/main.yml"
    name: shared

- name: Create .env file for docker
  ansible.builtin.file:
    path: "{{ shared.tmp_build_folder }}/.env"
    state: touch
    mode: '0600'
    owner: aclaretdev
    group: aclaretdev
  tags:
    - deploy
    - config

- name: Write env vars into the .env file
  ansible.builtin.lineinfile:
    dest: "{{ shared.tmp_build_folder }}/.env"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    mode: '0600'
  with_items:
    - key: DATABASE_URL
      value: "{{ ansible_env.DATABASE_URL }}"
    - key: DATABASE_NAME
      value: "{{ ansible_env.DATABASE_NAME }}"
    - key: DATABASE_USER
      value: "{{ ansible_env.DATABASE_USER }}"
    - key: DATABASE_PASSWORD
      value: "{{ ansible_env.DATABASE_PASSWORD }}"
    - key: SERVER_PORT
      value: "{{ ansible_env.SERVER_PORT }}"
    - key: ENV
      value: "{{ ansible_env.POSTHOG_SDK_API_KEY }}"
    - key: API_URL
      value: "{{ ansible_env.POSTHOG_SDK_API_KEY }}"
  tags:
    - deploy
    - config
