tibia_char_artifact: tibia-char-artifact
remote_home_path: /home/aclaretdev
tmp_build_folder: /home/aclaretdev/tmp_build
deploy_path: /opt/tibia-char/src
backup_path: /opt/tibia-char/backup
migrate_version: v4.17.1
migrate_sha256: 1c22a3940e724148ea2545b18f0e684f7c089a6431a33b5fda07c18f2e3e85b6
remote_admin_user: aclaretdev
ansible_repo_root: "{{ playbook_dir }}"
local_tmp_build_folder: "{{ playbook_dir }}/tmp_build"
local_backup_artifact_folder: "{{ playbook_dir }}/artifact_backup"

